apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki-stack
  annotations:
    argocd.argoproj.io/sync-wave: "-1"