controller:
  args:
    appResyncPeriod: 30

server:
  service:
    type: NodePort
    nodePortHttp: 30010
  additionalApplications:
    - name: app-of-apps
      namespace: argo-cd
      project: default
      destination:
        server: https://kubernetes.default.svc
      source:
        path: infrastructure/app-of-apps
        repoURL: https://github.com/ItsKev/k6-load-testing.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

configs:
  repositories:
    github-repo:
      url: https://github.com/ItsKev/k6-load-testing.git
  secret:
    argocdServerAdminPassword: $2a$12$ApLLTHCRv1HF9DQyXEYXludcUS6jW26STbqhUB6GpokbOdFO8drk6