kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080
  - containerPort: 30001
    hostPort: 8090
  - containerPort: 30002
    hostPort: 8091
  - containerPort: 30010
    hostPort: 9876